# Generated by Django 4.2.4 on 2023-11-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(max_length=50)),
                ('especialidad', models.CharField(max_length=250)),
                ('servicio', models.CharField(max_length=250)),
                ('profesional', models.CharField(max_length=250)),
                ('hora', models.TimeField(max_length=50)),
            ],
        ),
    ]
